/**
 * Tailwind CSS Configuration — Theme-reactive via CSS variables
 *
 * All color/typography/spacing/shadow values reference --ch-* CSS variables
 * generated by themeEngine.ts. When themes switch, Tailwind classes
 * automatically reflect the new values — no JS re-render needed.
 *
 * External themes imported via ThemeManifest JSON work automatically
 * because they produce the same --ch-* variable set.
 */
import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      /* ---- Colors: mapped from --ch-* CSS variables ---- */
      colors: {
        brand: {
          50:  "var(--ch-brand-50)",
          100: "var(--ch-brand-100)",
          200: "var(--ch-brand-200)",
          300: "var(--ch-brand-300)",
          400: "var(--ch-brand-400)",
          500: "var(--ch-brand-500)",
          600: "var(--ch-brand-600)",
          700: "var(--ch-brand-700)",
          800: "var(--ch-brand-800)",
          900: "var(--ch-brand-900)",
        },
        neutral: {
          0:   "var(--ch-neutral-0)",
          25:  "var(--ch-neutral-25)",
          50:  "var(--ch-neutral-50)",
          100: "var(--ch-neutral-100)",
          200: "var(--ch-neutral-200)",
          300: "var(--ch-neutral-300)",
          400: "var(--ch-neutral-400)",
          500: "var(--ch-neutral-500)",
          600: "var(--ch-neutral-600)",
          700: "var(--ch-neutral-700)",
          800: "var(--ch-neutral-800)",
          900: "var(--ch-neutral-900)",
          950: "var(--ch-neutral-950)",
        },
        success: {
          light: "var(--ch-success-light)",
          DEFAULT: "var(--ch-success-base)",
          dark: "var(--ch-success-dark)",
          text: "var(--ch-success-text)",
        },
        warning: {
          light: "var(--ch-warning-light)",
          DEFAULT: "var(--ch-warning-base)",
          dark: "var(--ch-warning-dark)",
          text: "var(--ch-warning-text)",
        },
        error: {
          light: "var(--ch-error-light)",
          DEFAULT: "var(--ch-error-base)",
          dark: "var(--ch-error-dark)",
          text: "var(--ch-error-text)",
        },
        info: {
          light: "var(--ch-info-light)",
          DEFAULT: "var(--ch-info-base)",
          dark: "var(--ch-info-dark)",
          text: "var(--ch-info-text)",
        },
        surface: {
          page: "var(--ch-surface-page)",
          card: "var(--ch-surface-card)",
          elevated: "var(--ch-surface-elevated)",
          inset: "var(--ch-surface-inset)",
          sidebar: "var(--ch-surface-sidebar)",
          "sidebar-hover": "var(--ch-surface-sidebarHover)",
          "sidebar-active": "var(--ch-surface-sidebarActive)",
        },
        border: {
          subtle: "var(--ch-border-subtle)",
          DEFAULT: "var(--ch-border-default)",
          strong: "var(--ch-border-strong)",
        },
        focus: "var(--ch-focus)",
      },

      /* ---- Typography ---- */
      fontFamily: {
        heading: "var(--ch-font-heading)",
        body: "var(--ch-font-body)",
        mono: "var(--ch-font-mono)",
      },
      fontSize: {
        xs: "var(--ch-text-xs)",
        sm: "var(--ch-text-sm)",
        base: "var(--ch-text-base)",
        md: "var(--ch-text-md)",
        lg: "var(--ch-text-lg)",
        xl: "var(--ch-text-xl)",
        "2xl": "var(--ch-text-2xl)",
        "3xl": "var(--ch-text-3xl)",
      },

      /* ---- Border Radius ---- */
      borderRadius: {
        sm: "var(--ch-radius-sm)",
        md: "var(--ch-radius-md)",
        lg: "var(--ch-radius-lg)",
        xl: "var(--ch-radius-xl)",
        full: "var(--ch-radius-full)",
      },

      /* ---- Shadows ---- */
      boxShadow: {
        xs: "var(--ch-shadow-xs)",
        sm: "var(--ch-shadow-sm)",
        md: "var(--ch-shadow-md)",
        lg: "var(--ch-shadow-lg)",
        xl: "var(--ch-shadow-xl)",
        "2xl": "var(--ch-shadow-2xl)",
      },

      /* ---- Layout ---- */
      width: {
        sidebar: "var(--ch-sidebar-width)",
        "sidebar-collapsed": "var(--ch-sidebar-collapsed-width)",
      },
      height: {
        header: "var(--ch-header-height)",
      },
      maxWidth: {
        page: "var(--ch-page-max-width)",
      },

      /* ---- Z-Index ---- */
      zIndex: {
        sidebar: "100",
        header: "110",
        dropdown: "200",
        modal: "300",
        "command-palette": "350",
        toast: "400",
      },

      /* ---- Transitions ---- */
      transitionDuration: {
        fast: "120ms",
        normal: "180ms",
        slow: "280ms",
      },

      /* ---- Animations ---- */
      keyframes: {
        "sheet-slide-in": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "sheet-fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "quicklook-scale-in": {
          from: { opacity: "0", transform: "translate(-50%, -50%) scale(0.95)" },
          to: { opacity: "1", transform: "translate(-50%, -50%) scale(1)" },
        },
        "toast-slide-in": {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "palette-enter": {
          from: { opacity: "0", transform: "translateY(-8px) scale(0.98)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "palette-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
      },
      animation: {
        "sheet-slide-in": "sheet-slide-in 220ms ease",
        "sheet-fade-in": "sheet-fade-in 180ms ease",
        "quicklook-scale-in": "quicklook-scale-in 180ms ease",
        "toast-slide-in": "toast-slide-in 220ms ease",
        "palette-enter": "palette-enter 120ms ease-out",
        "palette-pulse": "palette-pulse 1.2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
} satisfies Config;
