"""
Wizard Configuration seed data — M32.

Provides default wizard configs for news_bulletin and standard_video.
These are inserted when the table is first created or when seed is called.

Her alan icin:
  - field_key: backend alan adi
  - writes_to_backend: API'ye yaziliyor mu
  - affects_snapshot: job snapshot'a giriyor mu
  - affects_pipeline: render/pipeline davranisini etkiliyor mu
  - preview_enabled: wizard'da preview gosteriliyor mu
  - auto_suggest: otomatik oneri destegi var mi
"""

NEWS_BULLETIN_CONFIG = {
    "wizard_type": "news_bulletin",
    "display_name": "Haber Bulteni Wizard",
    "enabled": True,
    "module_scope": "news_bulletin",
    "steps_config": [
        {
            "step_key": "source",
            "label": "Kaynak & Haber Secimi",
            "order": 0,
            "enabled": True,
            "fields": [
                {
                    "field_key": "language",
                    "label": "Dil",
                    "field_type": "select",
                    "required": True,
                    "visible": True,
                    "admin_hideable": False,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": "tr",
                    "options": ["tr", "en"],
                    "help_text": "Bulten dili",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "tone",
                    "label": "Ton",
                    "field_type": "select",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": "formal",
                    "options": ["formal", "casual", "dramatic", "neutral"],
                    "help_text": "Anlatim tonu",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "target_duration_seconds",
                    "label": "Hedef Sure (sn)",
                    "field_type": "number",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": 120,
                    "options": None,
                    "help_text": "Hedef video suresi",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "topic",
                    "label": "Konu",
                    "field_type": "text",
                    "required": True,
                    "visible": True,
                    "admin_hideable": False,
                    "auto_suggest": True,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "Secilen haberlerden otomatik onerilir",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "title",
                    "label": "Baslik",
                    "field_type": "text",
                    "required": False,
                    "visible": False,
                    "admin_hideable": True,
                    "auto_suggest": True,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "Metadata asamasinda LLM tarafindan uretilir",
                    "writes_to_backend": True,
                    "affects_snapshot": False,
                    "affects_pipeline": False,
                },
                {
                    "field_key": "brief",
                    "label": "Aciklama",
                    "field_type": "textarea",
                    "required": False,
                    "visible": False,
                    "admin_hideable": True,
                    "auto_suggest": True,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "Metadata asamasinda LLM tarafindan uretilir",
                    "writes_to_backend": True,
                    "affects_snapshot": False,
                    "affects_pipeline": False,
                },
                {
                    "field_key": "news_selection",
                    "label": "Haber Secimi",
                    "field_type": "news_selector",
                    "required": True,
                    "visible": True,
                    "admin_hideable": False,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "Bultene dahil edilecek haberler",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
            ],
        },
        {
            "step_key": "review",
            "label": "Draft & Review",
            "order": 1,
            "enabled": True,
            "fields": [
                {
                    "field_key": "edited_narration",
                    "label": "Narration Duzenleme",
                    "field_type": "narration_editor",
                    "required": False,
                    "visible": True,
                    "admin_hideable": False,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "Her haber icin narration metni duzenlenebilir",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
            ],
        },
        {
            "step_key": "style",
            "label": "Stil & Uretim",
            "order": 2,
            "enabled": True,
            "fields": [
                {
                    "field_key": "render_mode",
                    "label": "Video Modu",
                    "field_type": "select",
                    "required": True,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": "combined",
                    "options": ["combined", "per_category", "per_item"],
                    "help_text": "Tek video, kategori bazli veya haber bazli cikti",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "subtitle_style",
                    "label": "Altyazi Stili",
                    "field_type": "subtitle_style",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": True,
                    "preview_enabled": True,
                    "default_value": "clean_white",
                    "options": ["clean_white", "bold_yellow", "minimal_dark", "gradient_glow", "outline_only"],
                    "help_text": "Altyazi gorsel stili — CSS preview ile",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "lower_third_style",
                    "label": "Alt Bant Stili",
                    "field_type": "lower_third_style",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": True,
                    "preview_enabled": True,
                    "default_value": "broadcast",
                    "options": ["broadcast", "minimal", "modern"],
                    "help_text": "Alt bant gorsel stili",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "trust_enforcement_level",
                    "label": "Guvenilirlik Denetimi",
                    "field_type": "trust_level",
                    "required": True,
                    "visible": True,
                    "admin_hideable": False,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": "warn",
                    "options": ["none", "warn", "block"],
                    "help_text": "Kaynak guvenilirlik kontrolu — trust check sonucu gosterilir",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "composition_direction",
                    "label": "Kompozisyon Yonu",
                    "field_type": "composition_direction",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": True,
                    "preview_enabled": True,
                    "default_value": None,
                    "options": ["classic", "side_by_side", "fullscreen", "dynamic"],
                    "help_text": "Video duzenleme yonu — ileride Remotion template'e baglanacak",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": False,
                },
                {
                    "field_key": "thumbnail_direction",
                    "label": "Thumbnail Yonu",
                    "field_type": "thumbnail_direction",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": True,
                    "preview_enabled": True,
                    "default_value": None,
                    "options": ["text_heavy", "image_heavy", "split", "minimal"],
                    "help_text": "Thumbnail stili — ileride Remotion template'e baglanacak",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": False,
                },
                {
                    "field_key": "style_blueprint_id",
                    "label": "Stil Sablonu",
                    "field_type": "blueprint_selector",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": None,
                    "options": None,
                    "help_text": "Stil sablonu secimi",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "template_id",
                    "label": "Sablon",
                    "field_type": "template_selector",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": None,
                    "options": None,
                    "help_text": "Icerik sablonu secimi",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
            ],
        },
    ],
    "field_defaults": {
        "language": "tr",
        "tone": "formal",
        "target_duration_seconds": 120,
        "render_mode": "combined",
        "subtitle_style": "clean_white",
        "lower_third_style": "broadcast",
        "trust_enforcement_level": "warn",
    },
}


STANDARD_VIDEO_CONFIG = {
    "wizard_type": "standard_video",
    "display_name": "Standart Video Wizard",
    "enabled": True,
    "module_scope": "standard_video",
    "steps_config": [
        {
            "step_key": "basics",
            "label": "Temel Bilgiler",
            "order": 0,
            "enabled": True,
            "fields": [
                {
                    "field_key": "topic",
                    "label": "Konu",
                    "field_type": "text",
                    "required": True,
                    "visible": True,
                    "admin_hideable": False,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "Video konusu",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "title",
                    "label": "Baslik",
                    "field_type": "text",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "Opsiyonel etiket",
                    "writes_to_backend": True,
                    "affects_snapshot": False,
                    "affects_pipeline": False,
                },
                {
                    "field_key": "brief",
                    "label": "Aciklama",
                    "field_type": "textarea",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "Kisa yonlendirme",
                    "writes_to_backend": True,
                    "affects_snapshot": False,
                    "affects_pipeline": False,
                },
                {
                    "field_key": "target_duration_seconds",
                    "label": "Hedef Sure (sn)",
                    "field_type": "number",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": 60,
                    "options": None,
                    "help_text": "Hedef video suresi",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "language",
                    "label": "Dil",
                    "field_type": "select",
                    "required": True,
                    "visible": True,
                    "admin_hideable": False,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": "tr",
                    "options": ["tr", "en"],
                    "help_text": "Video dili",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "tone",
                    "label": "Ton",
                    "field_type": "text",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "formal, casual, dramatic, vb.",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "visual_direction",
                    "label": "Gorsel Yon",
                    "field_type": "text",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": False,
                    "default_value": None,
                    "options": None,
                    "help_text": "clean, cinematic, minimal, vb.",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
            ],
        },
        {
            "step_key": "style",
            "label": "Stil Secimi",
            "order": 1,
            "enabled": True,
            "fields": [
                {
                    "field_key": "style_blueprint_id",
                    "label": "Stil Sablonu",
                    "field_type": "blueprint_selector",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": None,
                    "options": None,
                    "help_text": "Stil sablonu secimi",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
                {
                    "field_key": "composition_direction",
                    "label": "Kompozisyon Yonu",
                    "field_type": "composition_direction",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": None,
                    "options": ["classic", "side_by_side", "fullscreen", "dynamic"],
                    "help_text": "Video duzenleme yonu",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": False,
                },
                {
                    "field_key": "thumbnail_direction",
                    "label": "Thumbnail Yonu",
                    "field_type": "thumbnail_direction",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": None,
                    "options": ["text_heavy", "image_heavy", "split", "minimal"],
                    "help_text": "Thumbnail stili",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": False,
                },
                {
                    "field_key": "subtitle_style",
                    "label": "Altyazi Stili",
                    "field_type": "subtitle_style",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": "clean_white",
                    "options": ["clean_white", "bold_yellow", "minimal_dark", "gradient_glow", "outline_only"],
                    "help_text": "Altyazi gorsel stili",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
            ],
        },
        {
            "step_key": "template",
            "label": "Sablon",
            "order": 2,
            "enabled": True,
            "fields": [
                {
                    "field_key": "template_id",
                    "label": "Sablon",
                    "field_type": "template_selector",
                    "required": False,
                    "visible": True,
                    "admin_hideable": True,
                    "auto_suggest": False,
                    "preview_enabled": True,
                    "default_value": None,
                    "options": None,
                    "help_text": "Icerik sablonu secimi",
                    "writes_to_backend": True,
                    "affects_snapshot": True,
                    "affects_pipeline": True,
                },
            ],
        },
        {
            "step_key": "review",
            "label": "Onizleme",
            "order": 3,
            "enabled": True,
            "fields": [],
        },
    ],
    "field_defaults": {
        "language": "tr",
        "target_duration_seconds": 60,
        "subtitle_style": "clean_white",
    },
}


ALL_WIZARD_CONFIGS = [NEWS_BULLETIN_CONFIG, STANDARD_VIDEO_CONFIG]
