"""add news items table

Revision ID: 0ee09dfddce7
Revises: 5769e14d7322
Create Date: 2026-04-02 03:08:58.662417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee09dfddce7'
down_revision: Union[str, Sequence[str], None] = '5769e14d7322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_scan_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dedupe_key', sa.String(length=500), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_dedupe_key'), 'news_items', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_news_items_source_id'), 'news_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_news_items_source_scan_id'), 'news_items', ['source_scan_id'], unique=False)
    op.create_index(op.f('ix_news_items_status'), 'news_items', ['status'], unique=False)
    op.create_index(op.f('ix_news_items_url'), 'news_items', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_url'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_status'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_source_scan_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_source_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_dedupe_key'), table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
