"""add_standard_video_scripts_table

Revision ID: 2472507548c3
Revises: bf791934579f
Create Date: 2026-04-01 23:43:20.393844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2472507548c3'
down_revision: Union[str, Sequence[str], None] = 'bf791934579f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_video_scripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard_video_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_video_id'], ['standard_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_video_scripts_standard_video_id'), 'standard_video_scripts', ['standard_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standard_video_scripts_standard_video_id'), table_name='standard_video_scripts')
    op.drop_table('standard_video_scripts')
    # ### end Alembic commands ###
