"""add_templates_table

Revision ID: 2e7eb44ff9c8
Revises: f96474c7ec08
Create Date: 2026-04-02 01:25:35.796779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7eb44ff9c8'
down_revision: Union[str, Sequence[str], None] = 'f96474c7ec08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('owner_scope', sa.String(length=50), nullable=False),
    sa.Column('module_scope', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style_profile_json', sa.Text(), nullable=True),
    sa.Column('content_rules_json', sa.Text(), nullable=True),
    sa.Column('publish_profile_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_module_scope'), 'templates', ['module_scope'], unique=False)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    op.create_index(op.f('ix_templates_owner_scope'), 'templates', ['owner_scope'], unique=False)
    op.create_index(op.f('ix_templates_status'), 'templates', ['status'], unique=False)
    op.create_index(op.f('ix_templates_template_type'), 'templates', ['template_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_template_type'), table_name='templates')
    op.drop_index(op.f('ix_templates_status'), table_name='templates')
    op.drop_index(op.f('ix_templates_owner_scope'), table_name='templates')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_module_scope'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
