"""add_used_news_registry_table

Revision ID: 3771f6696ce2
Revises: 0ee09dfddce7
Create Date: 2026-04-02 03:14:39.966441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3771f6696ce2'
down_revision: Union[str, Sequence[str], None] = '0ee09dfddce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_news_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=False),
    sa.Column('usage_type', sa.String(length=100), nullable=False),
    sa.Column('usage_context', sa.Text(), nullable=True),
    sa.Column('target_module', sa.String(length=100), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_used_news_registry_news_item_id'), 'used_news_registry', ['news_item_id'], unique=False)
    op.create_index(op.f('ix_used_news_registry_target_module'), 'used_news_registry', ['target_module'], unique=False)
    op.create_index(op.f('ix_used_news_registry_usage_type'), 'used_news_registry', ['usage_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_used_news_registry_usage_type'), table_name='used_news_registry')
    op.drop_index(op.f('ix_used_news_registry_target_module'), table_name='used_news_registry')
    op.drop_index(op.f('ix_used_news_registry_news_item_id'), table_name='used_news_registry')
    op.drop_table('used_news_registry')
    # ### end Alembic commands ###
