"""add_news_bulletin_metadata_table

Revision ID: 3d2bdaf23628
Revises: 485edfc2f2b5
Create Date: 2026-04-02 03:40:21.431510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2bdaf23628'
down_revision: Union[str, Sequence[str], None] = '485edfc2f2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_bulletin_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('news_bulletin_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_bulletin_id'], ['news_bulletins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_bulletin_metadata_news_bulletin_id'), 'news_bulletin_metadata', ['news_bulletin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_bulletin_metadata_news_bulletin_id'), table_name='news_bulletin_metadata')
    op.drop_table('news_bulletin_metadata')
    # ### end Alembic commands ###
