"""add_news_bulletin_scripts_table

Revision ID: 485edfc2f2b5
Revises: 8c913edf5154
Create Date: 2026-04-02 03:35:48.648610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485edfc2f2b5'
down_revision: Union[str, Sequence[str], None] = '8c913edf5154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_bulletin_scripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('news_bulletin_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_bulletin_id'], ['news_bulletins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_bulletin_scripts_news_bulletin_id'), 'news_bulletin_scripts', ['news_bulletin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_bulletin_scripts_news_bulletin_id'), table_name='news_bulletin_scripts')
    op.drop_table('news_bulletin_scripts')
    # ### end Alembic commands ###
