"""add source scans table

Revision ID: 5769e14d7322
Revises: a1078575e258
Create Date: 2026-04-02 02:56:56.022616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5769e14d7322'
down_revision: Union[str, Sequence[str], None] = 'a1078575e258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('scan_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('raw_result_preview_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_scans_scan_mode'), 'source_scans', ['scan_mode'], unique=False)
    op.create_index(op.f('ix_source_scans_source_id'), 'source_scans', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_scans_status'), 'source_scans', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_scans_status'), table_name='source_scans')
    op.drop_index(op.f('ix_source_scans_source_id'), table_name='source_scans')
    op.drop_index(op.f('ix_source_scans_scan_mode'), table_name='source_scans')
    op.drop_table('source_scans')
    # ### end Alembic commands ###
