"""add_edited_narration_to_bulletin_selected_items

Revision ID: 5c6754cd1d40
Revises: cc4f6789756e
Create Date: 2026-04-06 17:51:26.196273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6754cd1d40'
down_revision: Union[str, Sequence[str], None] = 'cc4f6789756e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_bulletin_selected_items', sa.Column('edited_narration', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_bulletin_selected_items', 'edited_narration')
    # ### end Alembic commands ###
