"""add_style_blueprints_table

Revision ID: 705dbe9d9ef1
Revises: 2e7eb44ff9c8
Create Date: 2026-04-02 02:07:18.113496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705dbe9d9ef1'
down_revision: Union[str, Sequence[str], None] = '2e7eb44ff9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_blueprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('module_scope', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('visual_rules_json', sa.Text(), nullable=True),
    sa.Column('motion_rules_json', sa.Text(), nullable=True),
    sa.Column('layout_rules_json', sa.Text(), nullable=True),
    sa.Column('subtitle_rules_json', sa.Text(), nullable=True),
    sa.Column('thumbnail_rules_json', sa.Text(), nullable=True),
    sa.Column('preview_strategy_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_blueprints_module_scope'), 'style_blueprints', ['module_scope'], unique=False)
    op.create_index(op.f('ix_style_blueprints_name'), 'style_blueprints', ['name'], unique=False)
    op.create_index(op.f('ix_style_blueprints_status'), 'style_blueprints', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_blueprints_status'), table_name='style_blueprints')
    op.drop_index(op.f('ix_style_blueprints_name'), table_name='style_blueprints')
    op.drop_index(op.f('ix_style_blueprints_module_scope'), table_name='style_blueprints')
    op.drop_table('style_blueprints')
    # ### end Alembic commands ###
