"""add_news_bulletin_selected_items_table

Revision ID: 721a304e877f
Revises: 3d2bdaf23628
Create Date: 2026-04-02 04:01:54.670808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721a304e877f'
down_revision: Union[str, Sequence[str], None] = '3d2bdaf23628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_bulletin_selected_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('news_bulletin_id', sa.String(length=36), nullable=False),
    sa.Column('news_item_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_bulletin_id'], ['news_bulletins.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_bulletin_id', 'news_item_id', name='uq_bulletin_news_item')
    )
    op.create_index(op.f('ix_news_bulletin_selected_items_news_bulletin_id'), 'news_bulletin_selected_items', ['news_bulletin_id'], unique=False)
    op.create_index(op.f('ix_news_bulletin_selected_items_news_item_id'), 'news_bulletin_selected_items', ['news_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_bulletin_selected_items_news_item_id'), table_name='news_bulletin_selected_items')
    op.drop_index(op.f('ix_news_bulletin_selected_items_news_bulletin_id'), table_name='news_bulletin_selected_items')
    op.drop_table('news_bulletin_selected_items')
    # ### end Alembic commands ###
