"""faz2_add_domain_models_channel_project_engagement

Revision ID: 87a789ff3f45
Revises: dddfc15f2434
Create Date: 2026-04-09 00:16:17.776388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, text


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column already exists (SQLite partial migration recovery)."""
    bind = op.get_bind()
    insp = inspect(bind)
    columns = [c["name"] for c in insp.get_columns(table_name)]
    return column_name in columns


def _table_exists(table_name: str) -> bool:
    """Check if a table already exists (SQLite partial migration recovery)."""
    bind = op.get_bind()
    insp = inspect(bind)
    return table_name in insp.get_table_names()


def _index_exists(index_name: str, table_name: str) -> bool:
    """Check if an index already exists."""
    bind = op.get_bind()
    insp = inspect(bind)
    indexes = insp.get_indexes(table_name)
    return any(idx["name"] == index_name for idx in indexes)


# revision identifiers, used by Alembic.
revision: str = '87a789ff3f45'
down_revision: Union[str, Sequence[str], None] = 'dddfc15f2434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('palette', sa.Text(), nullable=True),
    sa.Column('typography', sa.Text(), nullable=True),
    sa.Column('motion_style', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('watermark_path', sa.Text(), nullable=True),
    sa.Column('watermark_position', sa.String(length=50), nullable=True),
    sa.Column('intro_template_id', sa.String(length=36), nullable=True),
    sa.Column('outro_template_id', sa.String(length=36), nullable=True),
    sa.Column('lower_third_defaults', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_owner_user_id'), 'brand_profiles', ['owner_user_id'], unique=False)
    op.create_table('channel_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('profile_type', sa.String(length=100), nullable=True),
    sa.Column('channel_slug', sa.String(length=100), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('default_content_mode', sa.String(length=100), nullable=True),
    sa.Column('brand_profile_id', sa.String(length=36), nullable=True),
    sa.Column('automation_policy_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_slug', name='uq_user_channel_slug')
    )
    op.create_index(op.f('ix_channel_profiles_channel_slug'), 'channel_profiles', ['channel_slug'], unique=False)
    op.create_index(op.f('ix_channel_profiles_user_id'), 'channel_profiles', ['user_id'], unique=False)
    op.create_table('automation_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_profile_id', sa.String(length=36), nullable=False),
    sa.Column('automation_level', sa.String(length=50), nullable=False),
    sa.Column('cp_source_scan', sa.String(length=50), nullable=False),
    sa.Column('cp_draft_generation', sa.String(length=50), nullable=False),
    sa.Column('cp_render', sa.String(length=50), nullable=False),
    sa.Column('cp_publish', sa.String(length=50), nullable=False),
    sa.Column('cp_post_publish', sa.String(length=50), nullable=False),
    sa.Column('publish_windows', sa.Text(), nullable=True),
    sa.Column('max_daily_posts', sa.Integer(), nullable=False),
    sa.Column('platform_specific_rules', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_profile_id'], ['channel_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_profile_id')
    )
    op.create_table('content_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel_profile_id', sa.String(length=36), nullable=False),
    sa.Column('module_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('content_status', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('publish_status', sa.String(length=50), nullable=False),
    sa.Column('primary_platform', sa.String(length=50), nullable=True),
    sa.Column('origin_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_job_id', sa.String(length=36), nullable=True),
    sa.Column('latest_output_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_profile_id'], ['channel_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_projects_channel_profile_id'), 'content_projects', ['channel_profile_id'], unique=False)
    op.create_index(op.f('ix_content_projects_module_type'), 'content_projects', ['module_type'], unique=False)
    op.create_index(op.f('ix_content_projects_user_id'), 'content_projects', ['user_id'], unique=False)
    op.create_table('platform_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_profile_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_account_id', sa.String(length=500), nullable=True),
    sa.Column('external_account_name', sa.String(length=500), nullable=True),
    sa.Column('external_avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('auth_state', sa.String(length=50), nullable=False),
    sa.Column('token_state', sa.String(length=50), nullable=False),
    sa.Column('scopes_granted', sa.Text(), nullable=True),
    sa.Column('scopes_required', sa.Text(), nullable=True),
    sa.Column('scope_status', sa.String(length=50), nullable=False),
    sa.Column('features_available', sa.Text(), nullable=True),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('requires_reauth', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_profile_id'], ['channel_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_connections_channel_profile_id'), 'platform_connections', ['channel_profile_id'], unique=False)
    op.create_index(op.f('ix_platform_connections_platform'), 'platform_connections', ['platform'], unique=False)
    op.create_table('engagement_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel_profile_id', sa.String(length=36), nullable=False),
    sa.Column('content_project_id', sa.String(length=36), nullable=True),
    sa.Column('platform_connection_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('target_object_type', sa.String(length=100), nullable=True),
    sa.Column('target_object_id', sa.String(length=500), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('final_user_input', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_profile_id'], ['channel_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_tasks_channel_profile_id'), 'engagement_tasks', ['channel_profile_id'], unique=False)
    op.create_index(op.f('ix_engagement_tasks_content_project_id'), 'engagement_tasks', ['content_project_id'], unique=False)
    op.create_index(op.f('ix_engagement_tasks_platform_connection_id'), 'engagement_tasks', ['platform_connection_id'], unique=False)
    op.create_index(op.f('ix_engagement_tasks_type'), 'engagement_tasks', ['type'], unique=False)
    op.create_index(op.f('ix_engagement_tasks_user_id'), 'engagement_tasks', ['user_id'], unique=False)
    op.create_table('platform_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform_connection_id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=500), nullable=True),
    sa.Column('client_secret', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('raw_token_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_connection_id')
    )
    # --- Add columns to existing tables (with existence checks for partial migration recovery) ---

    if not _column_exists('jobs', 'channel_profile_id'):
        op.add_column('jobs', sa.Column('channel_profile_id', sa.String(length=36), nullable=True))
    if not _column_exists('jobs', 'content_project_id'):
        op.add_column('jobs', sa.Column('content_project_id', sa.String(length=36), nullable=True))
    if not _column_exists('jobs', 'trigger_source'):
        op.add_column('jobs', sa.Column('trigger_source', sa.String(length=50), nullable=True))
    if not _index_exists('ix_jobs_channel_profile_id', 'jobs'):
        op.create_index(op.f('ix_jobs_channel_profile_id'), 'jobs', ['channel_profile_id'], unique=False)
    if not _index_exists('ix_jobs_content_project_id', 'jobs'):
        op.create_index(op.f('ix_jobs_content_project_id'), 'jobs', ['content_project_id'], unique=False)
    if not _index_exists('ix_jobs_is_test_data', 'jobs'):
        op.create_index(op.f('ix_jobs_is_test_data'), 'jobs', ['is_test_data'], unique=False)

    if not _column_exists('publish_records', 'content_project_id'):
        op.add_column('publish_records', sa.Column('content_project_id', sa.String(length=36), nullable=True))
    if not _column_exists('publish_records', 'platform_connection_id'):
        op.add_column('publish_records', sa.Column('platform_connection_id', sa.String(length=36), nullable=True))
    if not _column_exists('publish_records', 'publish_intent_json'):
        op.add_column('publish_records', sa.Column('publish_intent_json', sa.Text(), nullable=True))
    if not _column_exists('publish_records', 'publish_result_json'):
        op.add_column('publish_records', sa.Column('publish_result_json', sa.Text(), nullable=True))
    if not _index_exists('ix_publish_records_content_project_id', 'publish_records'):
        op.create_index(op.f('ix_publish_records_content_project_id'), 'publish_records', ['content_project_id'], unique=False)
    if not _index_exists('ix_publish_records_platform_connection_id', 'publish_records'):
        op.create_index(op.f('ix_publish_records_platform_connection_id'), 'publish_records', ['platform_connection_id'], unique=False)

    if not _column_exists('users', 'password_hash'):
        op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))

    if not _column_exists('video_stats_snapshots', 'platform_connection_id'):
        op.add_column('video_stats_snapshots', sa.Column('platform_connection_id', sa.String(length=36), nullable=True))
    if not _index_exists('ix_video_stats_snapshots_platform_connection_id', 'video_stats_snapshots'):
        op.create_index(op.f('ix_video_stats_snapshots_platform_connection_id'), 'video_stats_snapshots', ['platform_connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_stats_snapshots_platform_connection_id'), table_name='video_stats_snapshots')
    op.drop_column('video_stats_snapshots', 'platform_connection_id')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_publish_records_platform_connection_id'), table_name='publish_records')
    op.drop_index(op.f('ix_publish_records_content_project_id'), table_name='publish_records')
    op.drop_column('publish_records', 'publish_result_json')
    op.drop_column('publish_records', 'publish_intent_json')
    op.drop_column('publish_records', 'platform_connection_id')
    op.drop_column('publish_records', 'content_project_id')
    op.drop_index(op.f('ix_jobs_is_test_data'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_channel_profile_id'), table_name='jobs')
    op.drop_column('jobs', 'trigger_source')
    op.drop_column('jobs', 'content_project_id')
    op.drop_column('jobs', 'channel_profile_id')
    op.drop_table('platform_credentials')
    op.drop_index(op.f('ix_engagement_tasks_user_id'), table_name='engagement_tasks')
    op.drop_index(op.f('ix_engagement_tasks_type'), table_name='engagement_tasks')
    op.drop_index(op.f('ix_engagement_tasks_platform_connection_id'), table_name='engagement_tasks')
    op.drop_index(op.f('ix_engagement_tasks_content_project_id'), table_name='engagement_tasks')
    op.drop_index(op.f('ix_engagement_tasks_channel_profile_id'), table_name='engagement_tasks')
    op.drop_table('engagement_tasks')
    op.drop_index(op.f('ix_platform_connections_platform'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_channel_profile_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_content_projects_user_id'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_module_type'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_channel_profile_id'), table_name='content_projects')
    op.drop_table('content_projects')
    op.drop_table('automation_policies')
    op.drop_index(op.f('ix_channel_profiles_user_id'), table_name='channel_profiles')
    op.drop_index(op.f('ix_channel_profiles_channel_slug'), table_name='channel_profiles')
    op.drop_table('channel_profiles')
    op.drop_index(op.f('ix_brand_profiles_owner_user_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
