"""add_news_bulletins_table

Revision ID: 8c913edf5154
Revises: 3771f6696ce2
Create Date: 2026-04-02 03:20:01.711654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c913edf5154'
down_revision: Union[str, Sequence[str], None] = '3771f6696ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_bulletins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('bulletin_style', sa.String(length=100), nullable=True),
    sa.Column('source_mode', sa.String(length=50), nullable=True),
    sa.Column('selected_news_ids_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_bulletins_status'), 'news_bulletins', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_bulletins_status'), table_name='news_bulletins')
    op.drop_table('news_bulletins')
    # ### end Alembic commands ###
