"""add_template_style_links_table

Revision ID: 9d97ec750399
Revises: 721a304e877f
Create Date: 2026-04-02 12:19:02.711662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d97ec750399'
down_revision: Union[str, Sequence[str], None] = '721a304e877f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_style_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('style_blueprint_id', sa.String(length=36), nullable=False),
    sa.Column('link_role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['style_blueprint_id'], ['style_blueprints.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'style_blueprint_id', name='uq_template_style_blueprint')
    )
    op.create_index(op.f('ix_template_style_links_style_blueprint_id'), 'template_style_links', ['style_blueprint_id'], unique=False)
    op.create_index(op.f('ix_template_style_links_template_id'), 'template_style_links', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_style_links_template_id'), table_name='template_style_links')
    op.drop_index(op.f('ix_template_style_links_style_blueprint_id'), table_name='template_style_links')
    op.drop_table('template_style_links')
    # ### end Alembic commands ###
