"""add_news_sources_table

Revision ID: a1078575e258
Revises: 705dbe9d9ef1
Create Date: 2026-04-02 02:18:32.416071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1078575e258'
down_revision: Union[str, Sequence[str], None] = '705dbe9d9ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('feed_url', sa.String(length=500), nullable=True),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('trust_level', sa.String(length=50), nullable=True),
    sa.Column('scan_mode', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sources_name'), 'news_sources', ['name'], unique=False)
    op.create_index(op.f('ix_news_sources_scan_mode'), 'news_sources', ['scan_mode'], unique=False)
    op.create_index(op.f('ix_news_sources_source_type'), 'news_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_news_sources_status'), 'news_sources', ['status'], unique=False)
    op.create_index(op.f('ix_news_sources_trust_level'), 'news_sources', ['trust_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sources_trust_level'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_status'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_source_type'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_scan_mode'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_name'), table_name='news_sources')
    op.drop_table('news_sources')
    # ### end Alembic commands ###
