"""add video_stats_snapshots table

Revision ID: cc4f6789756e
Revises: c1a2b3d4e5f6
Create Date: 2026-04-05 16:01:39.655657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4f6789756e'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_stats_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform_video_id', sa.String(length=128), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_stats_snapshots_platform_video_id'), 'video_stats_snapshots', ['platform_video_id'], unique=False)
    op.create_index(op.f('ix_video_stats_snapshots_snapshot_at'), 'video_stats_snapshots', ['snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_stats_snapshots_snapshot_at'), table_name='video_stats_snapshots')
    op.drop_index(op.f('ix_video_stats_snapshots_platform_video_id'), table_name='video_stats_snapshots')
    op.drop_table('video_stats_snapshots')
    # ### end Alembic commands ###
