"""add_visibility_rules_table

Revision ID: de267292b2ab
Revises: f0dea9dfd155
Create Date: 2026-04-01 22:09:26.528393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de267292b2ab'
down_revision: Union[str, Sequence[str], None] = 'f0dea9dfd155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visibility_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('target_key', sa.String(length=255), nullable=False),
    sa.Column('module_scope', sa.String(length=100), nullable=True),
    sa.Column('role_scope', sa.String(length=50), nullable=True),
    sa.Column('mode_scope', sa.String(length=50), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('wizard_visible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_rules_rule_type'), 'visibility_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_visibility_rules_target_key'), 'visibility_rules', ['target_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visibility_rules_target_key'), table_name='visibility_rules')
    op.drop_index(op.f('ix_visibility_rules_rule_type'), table_name='visibility_rules')
    op.drop_table('visibility_rules')
    # ### end Alembic commands ###
