"""add_settings_table

Revision ID: f0dea9dfd155
Revises: e7dc18c0bcfb
Create Date: 2026-04-01 21:55:35.137233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dea9dfd155'
down_revision: Union[str, Sequence[str], None] = 'e7dc18c0bcfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('default_value_json', sa.Text(), nullable=False),
    sa.Column('admin_value_json', sa.Text(), nullable=False),
    sa.Column('user_override_allowed', sa.Boolean(), nullable=False),
    sa.Column('visible_to_user', sa.Boolean(), nullable=False),
    sa.Column('visible_in_wizard', sa.Boolean(), nullable=False),
    sa.Column('read_only_for_user', sa.Boolean(), nullable=False),
    sa.Column('module_scope', sa.String(length=100), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('validation_rules_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_group_name'), 'settings', ['group_name'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_group_name'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
